server:
  port: ${SERVER_PORT:8080}

spring:  data:    mongodb:      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}  elasticsearch:    rest:      password: changeme
      username: elastic
      
logging:  file: ./logs
  level: 
    kira: trace
    